### ISSUE TITLE
Assignment 8: On your marks. Get set. Hack!

### ISSUE THREAD

**Issue by dphiffer** [dphiffer/hacktivism#15]
*Due November 19*

![bake](https://user-images.githubusercontent.com/38114/68252444-9006a080-fff3-11e9-9509-3ec1287241b0.gif)

1. Meet with your group outside of class and hatch a plot.
2. Use hacktivism to enact your plot.

Criteria for success:
- Do you have a well-defined a justification for your hack?
- Have your tactics made full use of your collective talents and skills?
- Does the impact of your hack benefit those who are marginalized or who have less power?

**Comment by schafc** [comment]
For our hack, we decided to target the topic of issues here at RPI, focusing on the conflict between the administration and the student union, the security concerns inherent in SIS, and rushed implementation of the summer ARCH program. Our reason behind choosing this topic is that due to the fact students, on average, only stay at RPI for about 4 years, there is a cycle that occurs roughly every 5 years where the same problems keep occurring because all the students who remembers the previous issues are gone, so the administration is free to continue pushing their agenda. Additionally, we chose this topic because there is a distinct power imbalance between the students, who pay to be here, yet have very little power over what policies are enacted, and are only here for a relatively short period of time, and the administration, who are here all the time. Because of these factors, for our hack we decided to present the issues we felt were most relevant to this issue at the moment in the form of an informational flier, styled to resemble RPI’s marketing posters, that outlines the details we felt were most relevant to this issue. The plan is to post this to the RPI subreddit, where hopefully it will be seen by students who are considering attending RPI next fall, as it is around time when admissions decisions are coming out, and therefore inform them of the issues so they can be aware of the school environment that they will be a part of. Additionally, if able, we are hoping to send this out to alumni to increase awareness, however that will depend on if we are able to acquire their contact information.
Linked below is the flier we designed to present this information.
https://drive.google.com/file/d/1RbSVzBQuJd53UmzVHha3W6hQP4pBgHUA/view?usp=sharing
